spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/blogging_platform_dev
      database: blogging_platform_dev

app:
  cache:
    ttl-ms: 600000

logging:
  level:
    com.amalitech.SpringBootBloggingApp.security: INFO
    com.amalitech.SpringBootBloggingApp.service: INFO
